# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .get_application_parameters_by_app_generation_response_suggested_questions_after_answer import (
    GetApplicationParametersByAppGenerationResponseSuggestedQuestionsAfterAnswer,
)
from .get_application_parameters_by_app_generation_response_speech_to_text import (
    GetApplicationParametersByAppGenerationResponseSpeechToText,
)
from .get_application_parameters_by_app_generation_response_retriever_resource import (
    GetApplicationParametersByAppGenerationResponseRetrieverResource,
)
from .get_application_parameters_by_app_generation_response_annotation_reply import (
    GetApplicationParametersByAppGenerationResponseAnnotationReply,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetApplicationParametersByAppGenerationResponse(UniversalBaseModel):
    opening_statement: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opening statement
    """

    suggested_questions: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of suggested opening questions
    """

    suggested_questions_after_answer: typing.Optional[
        GetApplicationParametersByAppGenerationResponseSuggestedQuestionsAfterAnswer
    ] = pydantic.Field(default=None)
    """
    Settings for suggested questions after answer
    """

    speech_to_text: typing.Optional[GetApplicationParametersByAppGenerationResponseSpeechToText] = pydantic.Field(
        default=None
    )
    """
    Audio to text settings
    """

    retriever_resource: typing.Optional[GetApplicationParametersByAppGenerationResponseRetrieverResource] = (
        pydantic.Field(default=None)
    )
    """
    Citation and attribution settings
    """

    annotation_reply: typing.Optional[GetApplicationParametersByAppGenerationResponseAnnotationReply] = pydantic.Field(
        default=None
    )
    """
    Annotation reply settings
    """

    user_input_form: typing.Optional[typing.List[typing.Dict[str, typing.Optional[typing.Any]]]] = pydantic.Field(
        default=None
    )
    """
    User input form configuration
    """

    file_upload: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    File upload configuration
    """

    system_parameters: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    System parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
