# This file was auto-generated by Fern from our API Definition.

import typing
from .get_app_meta_info_by_app_generation_response_tool_icons_value_background import (
    GetAppMetaInfoByAppGenerationResponseToolIconsValueBackground,
)

GetAppMetaInfoByAppGenerationResponseToolIconsValue = typing.Union[
    GetAppMetaInfoByAppGenerationResponseToolIconsValueBackground, str
]
