# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .base_message_metadata import BaseMessageMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class BaseMessage(UniversalBaseModel):
    message_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique message ID
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    Message creation timestamp
    """

    metadata: typing.Optional[BaseMessageMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
