# This file was auto-generated by Fern from our API Definition.

from .base_message import BaseMessage
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ChatMessage(BaseMessage):
    conversation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Conversation ID
    """

    mode: typing.Optional[str] = pydantic.Field(default=None)
    """
    App mode, fixed as chat
    """

    answer: typing.Optional[str] = pydantic.Field(default=None)
    """
    Complete response content
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
