# This file was auto-generated by Fern from our API Definition.

import typing

CreateDocumentByFileRequestDataDocForm = typing.Union[
    typing.Literal["text_model", "hierarchical_model", "qa_model"], typing.Any
]
