# This file was auto-generated by Fern from our API Definition.

import typing

DocumentDisplayStatus = typing.Union[
    typing.Literal[
        "indexing",
        "index_failed",
        "indexed",
        "cleaning",
        "clean_failed",
        "cleaned",
        "parsing",
        "parse_failed",
        "parsed",
        "splitting",
        "split_failed",
        "splitted",
        "embedding",
        "embedding_failed",
        "embedded",
    ],
    typing.Any,
]
