# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class EmbeddingModelIconSmall(UniversalBaseModel):
    """
    Small icon
    """

    zh_hans: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="zh_Hans")] = pydantic.Field(
        default=None
    )
    """
    Chinese small icon
    """

    en_us: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="en_US")] = pydantic.Field(
        default=None
    )
    """
    English small icon
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
