# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ProcessRuleRulesPreProcessingRulesItem(UniversalBaseModel):
    """
    Pre-processing rules list
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for preprocessing rule
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this rule is selected
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rule name
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
