# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class RetrievalModelRerankingModel(UniversalBaseModel):
    """
    Rerank model configuration, optional, required if reranking is enabled
    """

    reranking_provider_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rerank model provider
    """

    reranking_model_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rerank model name
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
