# This file was auto-generated by Fern from our API Definition.

import typing

StreamEventEvent = typing.Union[
    typing.Literal[
        "workflow_started",
        "node_started",
        "node_finished",
        "workflow_finished",
        "tts_message",
        "tts_message_end",
        "ping",
    ],
    typing.Any,
]
