# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class StreamEventDataExecutionMetadata(UniversalBaseModel):
    """
    Metadata
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total tokens used
    """

    total_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total price
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency, such as USD / RMB
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
