# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .upload_document_data_source_type import UploadDocumentDataSourceType
import pydantic
from .upload_document_data_source_info_list_item import (
    UploadDocumentDataSourceInfoListItem,
)
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class UploadDocumentDataSource(UniversalBaseModel):
    type: typing.Optional[UploadDocumentDataSourceType] = pydantic.Field(default=None)
    """
    Document source type
    - upload_file: Upload file
    - notion_import: Notion import
    - notion_sync: Notion sync
    - web_page: Web page
    - web_site: Website
    - notion_page: Notion page
    - github_repository: GitHub repository
    Required, default: upload_file
    """

    info_list: typing.Optional[typing.List[UploadDocumentDataSourceInfoListItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
