# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .workflow_message_data_status import WorkflowMessageDataStatus
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class WorkflowMessageData(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workflow execution ID
    """

    workflow_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Associated Workflow ID
    """

    status: typing.Optional[WorkflowMessageDataStatus] = pydantic.Field(default=None)
    """
    Execution status
    """

    outputs: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Output content
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error reason
    """

    elapsed_time: typing.Optional[float] = pydantic.Field(default=None)
    """
    Elapsed time (s)
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total tokens used
    """

    total_steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total steps
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    Start time
    """

    finished_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    End time
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
