# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .workflow_message_data import WorkflowMessageData
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class WorkflowMessage(UniversalBaseModel):
    workflow_run_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workflow execution ID
    """

    task_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Task ID
    """

    data: typing.Optional[WorkflowMessageData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
