# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .get_workflow_logs_response_data_item import GetWorkflowLogsResponseDataItem
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetWorkflowLogsResponse(UniversalBaseModel):
    page: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current page number
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Items per page
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of records
    """

    has_more: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether there is more data
    """

    data: typing.Optional[typing.List[GetWorkflowLogsResponseDataItem]] = pydantic.Field(default=None)
    """
    Data for the current page
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
