# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .get_app_parameters_response_file_upload_image_transfer_methods_item import (
    GetAppParametersResponseFileUploadImageTransferMethodsItem,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetAppParametersResponseFileUploadImage(UniversalBaseModel):
    """
    Image settings
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether enabled
    """

    number_limits: typing.Optional[int] = pydantic.Field(default=None)
    """
    Image quantity limit, default 3
    """

    transfer_methods: typing.Optional[typing.List[GetAppParametersResponseFileUploadImageTransferMethodsItem]] = (
        pydantic.Field(default=None)
    )
    """
    Transfer method list
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
