# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .get_workflow_logs_response_data_item_workflow_run_status import (
    GetWorkflowLogsResponseDataItemWorkflowRunStatus,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetWorkflowLogsResponseDataItemWorkflowRun(UniversalBaseModel):
    """
    Workflow execution log
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Identifier
    """

    version: typing.Optional[str] = pydantic.Field(default=None)
    """
    Version
    """

    status: typing.Optional[GetWorkflowLogsResponseDataItemWorkflowRunStatus] = pydantic.Field(default=None)
    """
    Execution status
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error
    """

    elapsed_time: typing.Optional[float] = pydantic.Field(default=None)
    """
    Time elapsed, in seconds
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens consumed
    """

    total_steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of execution steps
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    Start time
    """

    finished_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    End time
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
