# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .get_app_parameters_response_file_upload_image import (
    GetAppParametersResponseFileUploadImage,
)
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetAppParametersResponseFileUpload(UniversalBaseModel):
    """
    File upload configuration
    """

    image: typing.Optional[GetAppParametersResponseFileUploadImage] = pydantic.Field(default=None)
    """
    Image settings
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
