# This file was auto-generated by Fern from our API Definition.

import typing

GetWorkflowLogsResponseDataItemWorkflowRunStatus = typing.Union[
    typing.Literal["running", "succeeded", "failed", "stopped"], typing.Any
]
