# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetAppParametersResponseSystemParameters(UniversalBaseModel):
    """
    System parameters
    """

    file_size_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Document upload size limit (MB)
    """

    image_file_size_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Image file upload size limit (MB)
    """

    audio_file_size_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio file upload size limit (MB)
    """

    video_file_size_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Video file upload size limit (MB)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
