# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetAppParametersResponseUserInputFormItemParagraph(UniversalBaseModel):
    """
    Paragraph text input control
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Control display label name
    """

    variable: typing.Optional[str] = pydantic.Field(default=None)
    """
    Control ID
    """

    required: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether required
    """

    default: typing.Optional[str] = pydantic.Field(default=None)
    """
    Default value
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
