# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class UploadFileResponse(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    File name
    """

    size: typing.Optional[int] = pydantic.Field(default=None)
    """
    File size (bytes)
    """

    extension: typing.Optional[str] = pydantic.Field(default=None)
    """
    File extension
    """

    mime_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    File mime-type
    """

    created_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Uploader ID
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    Upload time
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
