# This file was auto-generated by Fern from our API Definition.

import typing

GetConversationMessagesByAppAdvancedChatResponseDataItemFeedbackRating = typing.Union[
    typing.Literal["like", "dislike"], typing.Any
]
