# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .get_conversation_messages_by_app_advanced_chat_response_data_item_feedback_rating import (
    GetConversationMessagesByAppAdvancedChatResponseDataItemFeedbackRating,
)
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetConversationMessagesByAppAdvancedChatResponseDataItemFeedback(UniversalBaseModel):
    """
    Feedback information
    """

    rating: typing.Optional[GetConversationMessagesByAppAdvancedChatResponseDataItemFeedbackRating] = pydantic.Field(
        default=None
    )
    """
    Like or dislike
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
