# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .get_conversation_messages_by_app_advanced_chat_response_data_item_message_files_item_belongs_to import (
    GetConversationMessagesByAppAdvancedChatResponseDataItemMessageFilesItemBelongsTo,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetConversationMessagesByAppAdvancedChatResponseDataItemMessageFilesItem(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    File type, image for images
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Preview image URL
    """

    belongs_to: typing.Optional[GetConversationMessagesByAppAdvancedChatResponseDataItemMessageFilesItemBelongsTo] = (
        pydantic.Field(default=None)
    )
    """
    File owner, user or assistant
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
