# This file was auto-generated by Fern from our API Definition.

from .get_workspaces_current_models_model_types_text_embedding_response import (
    GetWorkspacesCurrentModelsModelTypesTextEmbeddingResponse,
)

__all__ = ["GetWorkspacesCurrentModelsModelTypesTextEmbeddingResponse"]
