# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .get_annotations_list_by_app_chat_response_data_item import (
    GetAnnotationsListByAppChatResponseDataItem,
)
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GetAnnotationsListByAppChatResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[GetAnnotationsListByAppChatResponseDataItem]] = None
    has_more: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether there is more data
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Items per page
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total record count
    """

    page: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current page number
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
