# This file was auto-generated by Fern from our API Definition.

import typing
from .get_app_meta_info_by_app_chat_response_tool_icons_value_background import (
    GetAppMetaInfoByAppChatResponseToolIconsValueBackground,
)

GetAppMetaInfoByAppChatResponseToolIconsValue = typing.Union[
    GetAppMetaInfoByAppChatResponseToolIconsValueBackground, str
]
