# This file was auto-generated by Fern from our API Definition.

import typing

GetConversationListByAppChatRequestSortBy = typing.Union[
    typing.Literal["created_at", "-created_at", "updated_at", "-updated_at"], typing.Any
]
