# This file was auto-generated by Fern from our API Definition.

import typing

SendChatMessageByAppChatRequestFilesItemTransferMethod = typing.Union[
    typing.Literal["remote_url", "local_file"], typing.Any
]
