# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.create_document_by_text_request_indexing_technique import (
    CreateDocumentByTextRequestIndexingTechnique,
)
from ..types.process_rule import ProcessRule
from .types.create_document_by_text_request_doc_form import (
    CreateDocumentByTextRequestDocForm,
)
from ..core.request_options import RequestOptions
from .types.create_document_by_text_response import CreateDocumentByTextResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.pydantic_utilities import parse_obj_as
from ..errors.bad_request_error import BadRequestError
from ..types.error import Error
from ..errors.content_too_large_error import ContentTooLargeError
from ..errors.unsupported_media_type_error import UnsupportedMediaTypeError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .. import core
from .types.create_document_by_file_response import CreateDocumentByFileResponse
from .types.update_document_by_text_request_indexing_technique import (
    UpdateDocumentByTextRequestIndexingTechnique,
)
from .types.update_document_by_text_request_doc_form import (
    UpdateDocumentByTextRequestDocForm,
)
from .types.update_document_by_text_response import UpdateDocumentByTextResponse
from ..errors.forbidden_error import ForbiddenError
from .types.update_document_by_file_response import UpdateDocumentByFileResponse
from .types.get_document_indexing_status_response import (
    GetDocumentIndexingStatusResponse,
)
from .types.get_document_list_response import GetDocumentListResponse
from .types.delete_document_response import DeleteDocumentResponse
from ..types.upload_file import UploadFile
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DocumentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_document_by_text(
        self,
        dataset_id: str,
        *,
        name: str,
        text: str,
        indexing_technique: CreateDocumentByTextRequestIndexingTechnique,
        process_rule: ProcessRule,
        doc_form: typing.Optional[CreateDocumentByTextRequestDocForm] = OMIT,
        doc_language: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDocumentByTextResponse:
        """
        Create a new document from text based on existing knowledge base

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        name : str
            Document name

        text : str
            Document content

        indexing_technique : CreateDocumentByTextRequestIndexingTechnique
            Indexing technique

        process_rule : ProcessRule

        doc_form : typing.Optional[CreateDocumentByTextRequestDocForm]
            Document form

        doc_language : typing.Optional[str]
            Document language (required for Q&A mode)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDocumentByTextResponse
            Successfully created document

        Examples
        --------
        from dify import DifyApi, ProcessRule

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.create_document_by_text(
            dataset_id="dataset_id",
            name="name",
            text="text",
            indexing_technique="high_quality",
            process_rule=ProcessRule(
                mode="automatic",
            ),
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/document/create-by-text",
            method="POST",
            json={
                "name": name,
                "text": text,
                "indexing_technique": indexing_technique,
                "doc_form": doc_form,
                "doc_language": doc_language,
                "process_rule": convert_and_respect_annotation_metadata(
                    object_=process_rule, annotation=ProcessRule, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateDocumentByTextResponse,
                    parse_obj_as(
                        type_=CreateDocumentByTextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 415:
                raise UnsupportedMediaTypeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_document_by_file(
        self,
        dataset_id: str,
        *,
        file: core.File,
        data: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDocumentByFileResponse:
        """
        Create a new document from file based on existing knowledge base

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        file : core.File
            See core.File for more documentation

        data : typing.Optional[str]
            Document configuration information in JSON string format, see CreateDocumentByFileRequestData schema for details

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDocumentByFileResponse
            Successfully created document

        Examples
        --------
        from dify import DifyApi

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.create_document_by_file(
            dataset_id="dataset_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/document/create-by-file",
            method="POST",
            data={
                "data": data,
            },
            files={
                "file": file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateDocumentByFileResponse,
                    parse_obj_as(
                        type_=CreateDocumentByFileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 415:
                raise UnsupportedMediaTypeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update_document_by_text(
        self,
        dataset_id: str,
        document_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        text: typing.Optional[str] = OMIT,
        indexing_technique: typing.Optional[UpdateDocumentByTextRequestIndexingTechnique] = OMIT,
        doc_form: typing.Optional[UpdateDocumentByTextRequestDocForm] = OMIT,
        doc_language: typing.Optional[str] = OMIT,
        process_rule: typing.Optional[ProcessRule] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateDocumentByTextResponse:
        """
        Update existing document using text

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        name : typing.Optional[str]
            Document name

        text : typing.Optional[str]
            Document content

        indexing_technique : typing.Optional[UpdateDocumentByTextRequestIndexingTechnique]
            Indexing technique

        doc_form : typing.Optional[UpdateDocumentByTextRequestDocForm]
            Document form

        doc_language : typing.Optional[str]
            Document language (required for Q&A mode)

        process_rule : typing.Optional[ProcessRule]
            Processing rules

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateDocumentByTextResponse
            Successfully updated document

        Examples
        --------
        from dify import DifyApi

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.update_document_by_text(
            dataset_id="dataset_id",
            document_id="document_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}/update-by-text",
            method="POST",
            json={
                "name": name,
                "text": text,
                "indexing_technique": indexing_technique,
                "doc_form": doc_form,
                "doc_language": doc_language,
                "process_rule": convert_and_respect_annotation_metadata(
                    object_=process_rule, annotation=ProcessRule, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UpdateDocumentByTextResponse,
                    parse_obj_as(
                        type_=UpdateDocumentByTextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update_document_by_file(
        self,
        dataset_id: str,
        document_id: str,
        *,
        file: core.File,
        name: typing.Optional[str] = OMIT,
        process_rule: typing.Optional[ProcessRule] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateDocumentByFileResponse:
        """
        Update existing document using file

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        file : core.File
            See core.File for more documentation

        name : typing.Optional[str]
            Document name

        process_rule : typing.Optional[ProcessRule]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateDocumentByFileResponse
            Successfully updated document

        Examples
        --------
        from dify import DifyApi

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.update_document_by_file(
            dataset_id="dataset_id",
            document_id="document_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}/update-by-file",
            method="POST",
            data={
                "name": name,
                "process_rule": process_rule.model_dump_json() if process_rule else None,
            },
            files={
                "file": file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UpdateDocumentByFileResponse,
                    parse_obj_as(
                        type_=UpdateDocumentByFileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 415:
                raise UnsupportedMediaTypeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_document_indexing_status(
        self,
        dataset_id: str,
        batch: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetDocumentIndexingStatusResponse:
        """
        Get document processing and indexing progress status

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        batch : str
            Document batch number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDocumentIndexingStatusResponse
            Successfully retrieved indexing status

        Examples
        --------
        from dify import DifyApi

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.get_document_indexing_status(
            dataset_id="dataset_id",
            batch="batch",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(batch)}/indexing-status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetDocumentIndexingStatusResponse,
                    parse_obj_as(
                        type_=GetDocumentIndexingStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_document_list(
        self,
        dataset_id: str,
        *,
        keyword: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetDocumentListResponse:
        """
        Get a list of all documents in the specified knowledge base

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        keyword : typing.Optional[str]
            Search keyword

        page : typing.Optional[int]
            Page number

        limit : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDocumentListResponse
            Successfully retrieved document list

        Examples
        --------
        from dify import DifyApi

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.get_document_list(
            dataset_id="dataset_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents",
            method="GET",
            params={
                "keyword": keyword,
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetDocumentListResponse,
                    parse_obj_as(
                        type_=GetDocumentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete_document(
        self,
        dataset_id: str,
        document_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteDocumentResponse:
        """
        Delete specified document

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteDocumentResponse
            Successfully deleted document

        Examples
        --------
        from dify import DifyApi

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.delete_document(
            dataset_id="dataset_id",
            document_id="document_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    DeleteDocumentResponse,
                    parse_obj_as(
                        type_=DeleteDocumentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_upload_file(
        self,
        dataset_id: str,
        document_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadFile:
        """
        Get upload file information of specified document

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadFile
            Successfully retrieved file information

        Examples
        --------
        from dify import DifyApi

        client = DifyApi(
            token="YOUR_TOKEN",
        )
        client.documents.get_upload_file(
            dataset_id="dataset_id",
            document_id="document_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}/upload-file",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UploadFile,
                    parse_obj_as(
                        type_=UploadFile,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncDocumentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_document_by_text(
        self,
        dataset_id: str,
        *,
        name: str,
        text: str,
        indexing_technique: CreateDocumentByTextRequestIndexingTechnique,
        process_rule: ProcessRule,
        doc_form: typing.Optional[CreateDocumentByTextRequestDocForm] = OMIT,
        doc_language: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDocumentByTextResponse:
        """
        Create a new document from text based on existing knowledge base

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        name : str
            Document name

        text : str
            Document content

        indexing_technique : CreateDocumentByTextRequestIndexingTechnique
            Indexing technique

        process_rule : ProcessRule

        doc_form : typing.Optional[CreateDocumentByTextRequestDocForm]
            Document form

        doc_language : typing.Optional[str]
            Document language (required for Q&A mode)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDocumentByTextResponse
            Successfully created document

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi, ProcessRule

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.create_document_by_text(
                dataset_id="dataset_id",
                name="name",
                text="text",
                indexing_technique="high_quality",
                process_rule=ProcessRule(
                    mode="automatic",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/document/create-by-text",
            method="POST",
            json={
                "name": name,
                "text": text,
                "indexing_technique": indexing_technique,
                "doc_form": doc_form,
                "doc_language": doc_language,
                "process_rule": convert_and_respect_annotation_metadata(
                    object_=process_rule, annotation=ProcessRule, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateDocumentByTextResponse,
                    parse_obj_as(
                        type_=CreateDocumentByTextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 415:
                raise UnsupportedMediaTypeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_document_by_file(
        self,
        dataset_id: str,
        *,
        file: core.File,
        data: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDocumentByFileResponse:
        """
        Create a new document from file based on existing knowledge base

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        file : core.File
            See core.File for more documentation

        data : typing.Optional[str]
            Document configuration information in JSON string format, see CreateDocumentByFileRequestData schema for details

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDocumentByFileResponse
            Successfully created document

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.create_document_by_file(
                dataset_id="dataset_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/document/create-by-file",
            method="POST",
            data={
                "data": data,
            },
            files={
                "file": file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    CreateDocumentByFileResponse,
                    parse_obj_as(
                        type_=CreateDocumentByFileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 415:
                raise UnsupportedMediaTypeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update_document_by_text(
        self,
        dataset_id: str,
        document_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        text: typing.Optional[str] = OMIT,
        indexing_technique: typing.Optional[UpdateDocumentByTextRequestIndexingTechnique] = OMIT,
        doc_form: typing.Optional[UpdateDocumentByTextRequestDocForm] = OMIT,
        doc_language: typing.Optional[str] = OMIT,
        process_rule: typing.Optional[ProcessRule] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateDocumentByTextResponse:
        """
        Update existing document using text

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        name : typing.Optional[str]
            Document name

        text : typing.Optional[str]
            Document content

        indexing_technique : typing.Optional[UpdateDocumentByTextRequestIndexingTechnique]
            Indexing technique

        doc_form : typing.Optional[UpdateDocumentByTextRequestDocForm]
            Document form

        doc_language : typing.Optional[str]
            Document language (required for Q&A mode)

        process_rule : typing.Optional[ProcessRule]
            Processing rules

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateDocumentByTextResponse
            Successfully updated document

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.update_document_by_text(
                dataset_id="dataset_id",
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}/update-by-text",
            method="POST",
            json={
                "name": name,
                "text": text,
                "indexing_technique": indexing_technique,
                "doc_form": doc_form,
                "doc_language": doc_language,
                "process_rule": convert_and_respect_annotation_metadata(
                    object_=process_rule, annotation=ProcessRule, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UpdateDocumentByTextResponse,
                    parse_obj_as(
                        type_=UpdateDocumentByTextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update_document_by_file(
        self,
        dataset_id: str,
        document_id: str,
        *,
        file: core.File,
        name: typing.Optional[str] = OMIT,
        process_rule: typing.Optional[ProcessRule] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateDocumentByFileResponse:
        """
        Update existing document using file

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        file : core.File
            See core.File for more documentation

        name : typing.Optional[str]
            Document name

        process_rule : typing.Optional[ProcessRule]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateDocumentByFileResponse
            Successfully updated document

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.update_document_by_file(
                dataset_id="dataset_id",
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}/update-by-file",
            method="POST",
            data={
                "name": name,
                "process_rule": process_rule.model_dump_json() if process_rule else None,
            },
            files={
                "file": file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UpdateDocumentByFileResponse,
                    parse_obj_as(
                        type_=UpdateDocumentByFileResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 415:
                raise UnsupportedMediaTypeError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_document_indexing_status(
        self,
        dataset_id: str,
        batch: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetDocumentIndexingStatusResponse:
        """
        Get document processing and indexing progress status

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        batch : str
            Document batch number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDocumentIndexingStatusResponse
            Successfully retrieved indexing status

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.get_document_indexing_status(
                dataset_id="dataset_id",
                batch="batch",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(batch)}/indexing-status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetDocumentIndexingStatusResponse,
                    parse_obj_as(
                        type_=GetDocumentIndexingStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_document_list(
        self,
        dataset_id: str,
        *,
        keyword: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetDocumentListResponse:
        """
        Get a list of all documents in the specified knowledge base

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        keyword : typing.Optional[str]
            Search keyword

        page : typing.Optional[int]
            Page number

        limit : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDocumentListResponse
            Successfully retrieved document list

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.get_document_list(
                dataset_id="dataset_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents",
            method="GET",
            params={
                "keyword": keyword,
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    GetDocumentListResponse,
                    parse_obj_as(
                        type_=GetDocumentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete_document(
        self,
        dataset_id: str,
        document_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteDocumentResponse:
        """
        Delete specified document

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteDocumentResponse
            Successfully deleted document

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.delete_document(
                dataset_id="dataset_id",
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    DeleteDocumentResponse,
                    parse_obj_as(
                        type_=DeleteDocumentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_upload_file(
        self,
        dataset_id: str,
        document_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadFile:
        """
        Get upload file information of specified document

        Parameters
        ----------
        dataset_id : str
            Knowledge Base ID

        document_id : str
            Document ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadFile
            Successfully retrieved file information

        Examples
        --------
        import asyncio

        from dify import AsyncDifyApi

        client = AsyncDifyApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.documents.get_upload_file(
                dataset_id="dataset_id",
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"datasets/{jsonable_encoder(dataset_id)}/documents/{jsonable_encoder(document_id)}/upload-file",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UploadFile,
                    parse_obj_as(
                        type_=UploadFile,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
